### ISSUE TITLE
Expressing forms with different URI scheme and transfer protocol

### ISSUE THREAD

**Issue by ektrah** [core-wg/coral#14]
In CoAP, it is possible to make CoAP requests to proxies and put a non-CoAP URI in the `Proxy-Uri` option.

At the moment, the draft contains language like "If the URI scheme indicates CoAP, then ... else ...". This would need to be cleaned up when allowing non-CoAP URI schemes as submission targets in forms submitted through CoAP.

(In theory, all of this also applies to HTTP, but, in practice, there is virtually no implementation support.)

**Comment by ektrah** [comment]
Maybe this is out of scope due to the decision to use a proxy generally being client-local...

**Comment by chrysn** [comment]
The current wording seems to hinder the use of cross-proxies, as it prescribes using CoAP methods on `coap://` URIs and HTTP methods on `http://` URIs.

We can't generalize over the protocols, probably (CoAP has FETCH, HTTP has PROPFIND – we can construct PROFIND forms, can't we?), but we may be able to relax the choice of methods to the point where it's helpful for constrained devices that use a C-H proxy to access Big Web resources.

Then, when the indicated method does not match the protocol, the device needs to either use a cross-proxy, or act as a cross-proxy to itself – but that may be easier for the device (it can CoAP-GET to its one-and-only gateway C-H forward proxy rather than thinking HTTP and H-C proxying internally), and at the very least indicates that it's OK to cross-proxy here.

**Comment by ektrah** [comment]
The current idea is to define protocol-specific vocabularies, e.g.:

```turtle
@using htv = <http://coreapps.org/protocol/http#>
turn-on() <http://device.example/turn-on> {
  htv:method "POST"
}
```

or

```turtle
@using htv = <http://coreapps.org/protocol/http#>
turn-on() <http://device.example/turn-on> {
  htv:method htv:POST
}
```

**Comment by ektrah** [comment]
Protocol-specific vocabularies have been implemented in [I-D.hartke-t2trg-coral-09](https://tools.ietf.org/html/draft-hartke-t2trg-coral-09). That should resolve this issue.
