### ISSUE TITLE
is  /a/b/c/../../d/f/g supposed to be encodable without normalization?

### ISSUE THREAD

**Issue by jimsch** [core-wg/coral#35]
Path is not permitted to have "." or ".." so the absolute path in in the title would not be encodable without first processing them.   Is this intentional?   If it is, then I don't think any document changes are needed

**Comment by ektrah** [comment]
Yes, this is intentional.

I view relative URI references as a compression method for URIs. As a result, not all URI references map 1:1 to the CBOR encoding. The way to convert a relative URI reference to CBOR is to resolve it against its base URI, convert it to a sequence of options, and then make it relative to its base URI again.
